/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.csusm;

import java.util.ArrayList;

/**
 *
 * @author carterrath
 */
public class HomeScreen extends javax.swing.JFrame {
    KeyManager km;
    User u;
    ArrayList<String[]> sites = new ArrayList<String[]>();
    /**
     * Creates new form HomeScreen
     */
    public HomeScreen() {
        initComponents();
        pack();
        setLocationRelativeTo(null); // set location to center of screen
        this.setVisible(true);
        //this.getRootPane().setDefaultButton(loginButton); // set enter key for button
    }
    public HomeScreen(User u) {
        this.u = u;
        km = KeyManager.getInstance();
        initComponents();
        setLocationRelativeTo(null); // set location to center of screen
        this.setVisible(true);
        changePassPanel.setVisible(false);
        addPanel.setVisible(false);
        editPanel.setVisible(false);
        deletePanel.setVisible(false);
        allPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homePanel = new javax.swing.JPanel();
        homeTitle = new javax.swing.JLabel();
        accountManageLabel = new javax.swing.JLabel();
        passManageLabel = new javax.swing.JLabel();
        changePassButton = new javax.swing.JButton();
        addPassButton = new javax.swing.JButton();
        deletePassButton = new javax.swing.JButton();
        editPassButton = new javax.swing.JButton();
        viewPassButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        sidePanel = new javax.swing.JLayeredPane();
        changePassPanel = new javax.swing.JPanel();
        changePassLabel = new javax.swing.JLabel();
        oldPassLabel = new javax.swing.JLabel();
        newPassLabel = new javax.swing.JLabel();
        changeAccountSaveButton = new javax.swing.JButton();
        changeAccountDoneButton = new javax.swing.JButton();
        passIncorrect = new javax.swing.JLabel();
        passwordUpdate = new javax.swing.JLabel();
        oldPassText = new javax.swing.JPasswordField();
        newPassText = new javax.swing.JPasswordField();
        addPanel = new javax.swing.JPanel();
        addPassTitle = new javax.swing.JLabel();
        savedPass = new javax.swing.JLabel();
        passNameLabel = new javax.swing.JLabel();
        passNameText = new javax.swing.JTextField();
        addDoneButton = new javax.swing.JButton();
        addSaveButton = new javax.swing.JButton();
        encryptionComboBox = new javax.swing.JComboBox<>();
        addPassLabel = new javax.swing.JLabel();
        encyrptionTypeLabel1 = new javax.swing.JLabel();
        addRedoButton = new javax.swing.JButton();
        addUndoButton = new javax.swing.JButton();
        encyrptionTypeLabel2 = new javax.swing.JLabel();
        addPassText = new javax.swing.JPasswordField();
        editPanel = new javax.swing.JPanel();
        editTitle = new javax.swing.JLabel();
        enterNameLabel = new javax.swing.JLabel();
        updatePassLabel = new javax.swing.JLabel();
        enterNameText = new javax.swing.JTextField();
        editSaveButton = new javax.swing.JButton();
        editDoneButton = new javax.swing.JButton();
        editUndoButton = new javax.swing.JButton();
        editRedoButton = new javax.swing.JButton();
        passwordUpdated = new javax.swing.JLabel();
        updatePassText = new javax.swing.JPasswordField();
        deletePanel = new javax.swing.JPanel();
        deleteTitle = new javax.swing.JLabel();
        deleteLabel = new javax.swing.JLabel();
        deleteText = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        deleteDoneButton = new javax.swing.JButton();
        deleteRedoButton = new javax.swing.JButton();
        deleteUndoButton = new javax.swing.JButton();
        passwordDeleted = new javax.swing.JLabel();
        allPanel = new javax.swing.JPanel();
        allPassTitle = new javax.swing.JLabel();
        allDoneButton = new javax.swing.JButton();
        allNameLabel = new javax.swing.JLabel();
        allPassLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        allPass = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        homePanel.setBackground(new java.awt.Color(153, 204, 255));

        homeTitle.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 24)); // NOI18N
        homeTitle.setText("SafeKey");

        accountManageLabel.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        accountManageLabel.setText("Account Management");

        passManageLabel.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        passManageLabel.setText("Password Management");

        changePassButton.setBackground(new java.awt.Color(0, 0, 0));
        changePassButton.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        changePassButton.setForeground(new java.awt.Color(153, 204, 255));
        changePassButton.setText("Change Password");
        changePassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePassButtonActionPerformed(evt);
            }
        });

        addPassButton.setBackground(new java.awt.Color(0, 0, 0));
        addPassButton.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        addPassButton.setForeground(new java.awt.Color(153, 204, 255));
        addPassButton.setText("Add Password");
        addPassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPassButtonActionPerformed(evt);
            }
        });

        deletePassButton.setBackground(new java.awt.Color(0, 0, 0));
        deletePassButton.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        deletePassButton.setForeground(new java.awt.Color(153, 204, 255));
        deletePassButton.setText("Delete Password");
        deletePassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePassButtonActionPerformed(evt);
            }
        });

        editPassButton.setBackground(new java.awt.Color(0, 0, 0));
        editPassButton.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        editPassButton.setForeground(new java.awt.Color(153, 204, 255));
        editPassButton.setText("Edit Password");
        editPassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPassButtonActionPerformed(evt);
            }
        });

        viewPassButton.setBackground(new java.awt.Color(0, 0, 0));
        viewPassButton.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        viewPassButton.setForeground(new java.awt.Color(153, 204, 255));
        viewPassButton.setText("View All Passwords");
        viewPassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    viewPassButtonActionPerformed(evt);
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
            }
        });

        logOutButton.setBackground(new java.awt.Color(0, 0, 0));
        logOutButton.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        logOutButton.setForeground(new java.awt.Color(153, 204, 255));
        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        changePassPanel.setBackground(new java.awt.Color(153, 204, 255));

        changePassLabel.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 14)); // NOI18N
        changePassLabel.setText("Change Account Password");

        oldPassLabel.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        oldPassLabel.setText("Enter Old Password");

        newPassLabel.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        newPassLabel.setText("Enter New Password");

        changeAccountSaveButton.setBackground(new java.awt.Color(0, 0, 0));
        changeAccountSaveButton.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        changeAccountSaveButton.setForeground(new java.awt.Color(153, 204, 255));
        changeAccountSaveButton.setText("Save");
        changeAccountSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    changeAccountSaveButtonActionPerformed(evt);
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
            }
        });

        changeAccountDoneButton.setBackground(new java.awt.Color(0, 0, 0));
        changeAccountDoneButton.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        changeAccountDoneButton.setForeground(new java.awt.Color(153, 204, 255));
        changeAccountDoneButton.setText("Done");
        changeAccountDoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeAccountDoneButtonActionPerformed(evt);
            }
        });

        passIncorrect.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        passIncorrect.setForeground(new java.awt.Color(255, 0, 51));
        passIncorrect.setText("Old Password Incorrect");

        passwordUpdate.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        passwordUpdate.setText("Password Updated");

        javax.swing.GroupLayout changePassPanelLayout = new javax.swing.GroupLayout(changePassPanel);
        changePassPanel.setLayout(changePassPanelLayout);
        changePassPanelLayout.setHorizontalGroup(
            changePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePassPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(oldPassLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, changePassPanelLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(changePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, changePassPanelLayout.createSequentialGroup()
                        .addGroup(changePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(changePassLabel)
                            .addGroup(changePassPanelLayout.createSequentialGroup()
                                .addGroup(changePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(changePassPanelLayout.createSequentialGroup()
                                        .addComponent(changeAccountSaveButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(changeAccountDoneButton))
                                    .addGroup(changePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(passIncorrect)
                                        .addComponent(newPassLabel)
                                        .addComponent(oldPassText, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(newPassText)))
                                .addGap(12, 12, 12)))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, changePassPanelLayout.createSequentialGroup()
                        .addComponent(passwordUpdate)
                        .addGap(55, 55, 55))))
        );
        changePassPanelLayout.setVerticalGroup(
            changePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePassPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(changePassLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(oldPassLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passIncorrect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oldPassText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newPassLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newPassText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(changePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeAccountDoneButton)
                    .addComponent(changeAccountSaveButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordUpdate)
                .addGap(11, 11, 11))
        );

        addPanel.setBackground(new java.awt.Color(153, 204, 255));

        addPassTitle.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 14)); // NOI18N
        addPassTitle.setText("Add New Password");

        savedPass.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        savedPass.setText("Saved Password: ");

        passNameLabel.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        passNameLabel.setText("Website Name");

        passNameText.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N

        addDoneButton.setBackground(new java.awt.Color(0, 0, 0));
        addDoneButton.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        addDoneButton.setForeground(new java.awt.Color(153, 204, 255));
        addDoneButton.setText("Done");
        addDoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDoneButtonActionPerformed(evt);
            }
        });

        addSaveButton.setBackground(new java.awt.Color(0, 0, 0));
        addSaveButton.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        addSaveButton.setForeground(new java.awt.Color(153, 204, 255));
        addSaveButton.setText("Add");
        addSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSaveButtonActionPerformed(evt);
            }
        });

        encryptionComboBox.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        encryptionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AES", "BlowFish" }));

        addPassLabel.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        addPassLabel.setText("Password");

        encyrptionTypeLabel1.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        encyrptionTypeLabel1.setText("Encryption Type");

        addRedoButton.setBackground(new java.awt.Color(0, 0, 0));
        addRedoButton.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        addRedoButton.setForeground(new java.awt.Color(153, 204, 255));
        addRedoButton.setText("Redo");
        addRedoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRedoButtonActionPerformed(evt);
            }
        });

        addUndoButton.setBackground(new java.awt.Color(0, 0, 0));
        addUndoButton.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        addUndoButton.setForeground(new java.awt.Color(153, 204, 255));
        addUndoButton.setText("Undo");
        addUndoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUndoButtonActionPerformed(evt);
            }
        });

        encyrptionTypeLabel2.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPanelLayout.createSequentialGroup()
                .addGap(0, 59, Short.MAX_VALUE)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addSaveButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addUndoButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addDoneButton)
                    .addComponent(addRedoButton))
                .addGap(43, 43, 43))
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passNameLabel)
                            .addComponent(passNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(encryptionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addPassLabel)
                            .addComponent(encyrptionTypeLabel1)
                            .addComponent(addPassText, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(addPassTitle))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(savedPass)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(addPanelLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(encyrptionTypeLabel2)
                    .addContainerGap(224, Short.MAX_VALUE)))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(addPassTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addPassLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addPassText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(encyrptionTypeLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(encryptionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(savedPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRedoButton)
                    .addComponent(addUndoButton))
                .addGap(5, 5, 5)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSaveButton)
                    .addComponent(addDoneButton))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPanelLayout.createSequentialGroup()
                    .addContainerGap(245, Short.MAX_VALUE)
                    .addComponent(encyrptionTypeLabel2)
                    .addGap(71, 71, 71)))
        );

        editPanel.setBackground(new java.awt.Color(153, 204, 255));

        editTitle.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 14)); // NOI18N
        editTitle.setText("Edit Password");

        enterNameLabel.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 12)); // NOI18N
        enterNameLabel.setText("Enter Name");

        updatePassLabel.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 12)); // NOI18N
        updatePassLabel.setText("New Password");

        enterNameText.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N

        editSaveButton.setBackground(new java.awt.Color(0, 0, 0));
        editSaveButton.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        editSaveButton.setForeground(new java.awt.Color(153, 204, 255));
        editSaveButton.setText("Save");
        editSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSaveButtonActionPerformed(evt);
            }
        });

        editDoneButton.setBackground(new java.awt.Color(0, 0, 0));
        editDoneButton.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        editDoneButton.setForeground(new java.awt.Color(153, 204, 255));
        editDoneButton.setText("Done");
        editDoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDoneButtonActionPerformed(evt);
            }
        });

        editUndoButton.setBackground(new java.awt.Color(0, 0, 0));
        editUndoButton.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        editUndoButton.setForeground(new java.awt.Color(153, 204, 255));
        editUndoButton.setText("Undo");
        editUndoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUndoButtonActionPerformed(evt);
            }
        });

        editRedoButton.setBackground(new java.awt.Color(0, 0, 0));
        editRedoButton.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        editRedoButton.setForeground(new java.awt.Color(153, 204, 255));
        editRedoButton.setText("Redo");
        editRedoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editRedoButtonActionPerformed(evt);
            }
        });

        passwordUpdated.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 12)); // NOI18N
        passwordUpdated.setText("Password Updated");

        javax.swing.GroupLayout editPanelLayout = new javax.swing.GroupLayout(editPanel);
        editPanel.setLayout(editPanelLayout);
        editPanelLayout.setHorizontalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPanelLayout.createSequentialGroup()
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(updatePassLabel)
                            .addComponent(enterNameLabel)
                            .addComponent(enterNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(updatePassText)))
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addContainerGap(64, Short.MAX_VALUE)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editUndoButton)
                            .addComponent(editSaveButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editDoneButton)
                            .addComponent(editRedoButton))))
                .addGap(44, 44, 44))
            .addGroup(editPanelLayout.createSequentialGroup()
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(editTitle))
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(passwordUpdated)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        editPanelLayout.setVerticalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(editTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enterNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updatePassLabel)
                .addGap(4, 4, 4)
                .addComponent(updatePassText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordUpdated)
                .addGap(10, 10, 10)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editUndoButton)
                    .addComponent(editRedoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editSaveButton)
                    .addComponent(editDoneButton))
                .addGap(25, 25, 25))
        );

        deletePanel.setBackground(new java.awt.Color(153, 204, 255));

        deleteTitle.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 14)); // NOI18N
        deleteTitle.setText("Delete Password");

        deleteLabel.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 12)); // NOI18N
        deleteLabel.setText("Enter Website Name to Delete");

        deleteText.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N

        deleteButton.setBackground(new java.awt.Color(0, 0, 0));
        deleteButton.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(153, 204, 255));
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        deleteDoneButton.setBackground(new java.awt.Color(0, 0, 0));
        deleteDoneButton.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        deleteDoneButton.setForeground(new java.awt.Color(153, 204, 255));
        deleteDoneButton.setText("Done");
        deleteDoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDoneButtonActionPerformed(evt);
            }
        });

        deleteRedoButton.setBackground(new java.awt.Color(0, 0, 0));
        deleteRedoButton.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        deleteRedoButton.setForeground(new java.awt.Color(153, 204, 255));
        deleteRedoButton.setText("Redo");
        deleteRedoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRedoButtonActionPerformed(evt);
            }
        });

        deleteUndoButton.setBackground(new java.awt.Color(0, 0, 0));
        deleteUndoButton.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        deleteUndoButton.setForeground(new java.awt.Color(153, 204, 255));
        deleteUndoButton.setText("Undo");
        deleteUndoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUndoButtonActionPerformed(evt);
            }
        });

        passwordDeleted.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 12)); // NOI18N
        passwordDeleted.setText("Password Deleted");

        javax.swing.GroupLayout deletePanelLayout = new javax.swing.GroupLayout(deletePanel);
        deletePanel.setLayout(deletePanelLayout);
        deletePanelLayout.setHorizontalGroup(
            deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deletePanelLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deletePanelLayout.createSequentialGroup()
                        .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(deletePanelLayout.createSequentialGroup()
                                .addComponent(deleteUndoButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteRedoButton)
                                .addGap(12, 12, 12))
                            .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(deleteText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(deletePanelLayout.createSequentialGroup()
                                    .addComponent(deleteButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(deleteDoneButton))))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deletePanelLayout.createSequentialGroup()
                        .addComponent(deleteLabel)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deletePanelLayout.createSequentialGroup()
                        .addComponent(deleteTitle)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deletePanelLayout.createSequentialGroup()
                        .addComponent(passwordDeleted)
                        .addGap(69, 69, 69))))
        );
        deletePanelLayout.setVerticalGroup(
            deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletePanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(deleteTitle)
                .addGap(37, 37, 37)
                .addComponent(deleteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordDeleted)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteRedoButton)
                    .addComponent(deleteUndoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(deleteDoneButton))
                .addGap(51, 51, 51))
        );

        allPanel.setBackground(new java.awt.Color(153, 204, 255));

        allPassTitle.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 14)); // NOI18N
        allPassTitle.setText("All Passwords");

        allDoneButton.setBackground(new java.awt.Color(0, 0, 0));
        allDoneButton.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        allDoneButton.setForeground(new java.awt.Color(153, 204, 255));
        allDoneButton.setText("Done");
        allDoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allDoneButtonActionPerformed(evt);
            }
        });

        allNameLabel.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 14)); // NOI18N
        allNameLabel.setText("Name");

        allPassLabel.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 14)); // NOI18N
        allPassLabel.setText("Password");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        allPass.setColumns(20);
        allPass.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        allPass.setRows(5);
        jScrollPane2.setViewportView(allPass);

        javax.swing.GroupLayout allPanelLayout = new javax.swing.GroupLayout(allPanel);
        allPanel.setLayout(allPanelLayout);
        allPanelLayout.setHorizontalGroup(
            allPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allPanelLayout.createSequentialGroup()
                .addGroup(allPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(allPanelLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(allDoneButton))
                    .addGroup(allPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, allPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(allNameLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(allPassLabel))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, allPanelLayout.createSequentialGroup()
                            .addGap(73, 73, 73)
                            .addComponent(allPassTitle)))
                    .addGroup(allPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        allPanelLayout.setVerticalGroup(
            allPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(allPassTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(allPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allPassLabel)
                    .addComponent(allNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(allDoneButton)
                .addGap(23, 23, 23))
        );

        sidePanel.setLayer(changePassPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sidePanel.setLayer(addPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sidePanel.setLayer(editPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sidePanel.setLayer(deletePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sidePanel.setLayer(allPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
            .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(changePassPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(addPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(editPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(deletePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(allPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(changePassPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(addPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(editPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(deletePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(allPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(homeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(logOutButton)
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accountManageLabel)
                            .addComponent(viewPassButton)
                            .addComponent(editPassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deletePassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addPassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passManageLabel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(changePassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(sidePanel))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logOutButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sidePanel)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addComponent(accountManageLabel)
                        .addGap(18, 18, 18)
                        .addComponent(changePassButton)
                        .addGap(27, 27, 27)
                        .addComponent(passManageLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addPassButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deletePassButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editPassButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewPassButton)
                        .addContainerGap(89, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changePassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePassButtonActionPerformed
        addPanel.setVisible(false);
        editPanel.setVisible(false);
        deletePanel.setVisible(false);
        allPanel.setVisible(false);
        passIncorrect.setVisible(false);
        passwordUpdate.setVisible(false);
        changePassPanel.setVisible(true);
        passwordUpdated.setVisible(false);
        savedPass.setVisible(false);
        passwordDeleted.setVisible(false);
    }//GEN-LAST:event_changePassButtonActionPerformed

    private void addPassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPassButtonActionPerformed
        changePassPanel.setVisible(false);
        editPanel.setVisible(false);
        deletePanel.setVisible(false);
        allPanel.setVisible(false);
        passwordUpdated.setVisible(false);
        savedPass.setVisible(false);
        passwordDeleted.setVisible(false);
        addPanel.setVisible(true);

    }//GEN-LAST:event_addPassButtonActionPerformed

    private void deletePassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePassButtonActionPerformed
        changePassPanel.setVisible(false);
        addPanel.setVisible(false);
        editPanel.setVisible(false);
        allPanel.setVisible(false);
        passwordUpdated.setVisible(false);
        savedPass.setVisible(false);
        passwordDeleted.setVisible(false);
        deletePanel.setVisible(true);
    }//GEN-LAST:event_deletePassButtonActionPerformed

    private void editPassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPassButtonActionPerformed
        changePassPanel.setVisible(false);
        addPanel.setVisible(false);
        deletePanel.setVisible(false);
        allPanel.setVisible(false);
        passwordUpdated.setVisible(false);
        savedPass.setVisible(false);
        passwordDeleted.setVisible(false);
        editPanel.setVisible(true);
    }//GEN-LAST:event_editPassButtonActionPerformed

    private void viewPassButtonActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_viewPassButtonActionPerformed
        allPass.setText("");
        changePassPanel.setVisible(false);
        addPanel.setVisible(false);
        editPanel.setVisible(false);
        deletePanel.setVisible(false);
        passwordUpdated.setVisible(false);
        savedPass.setVisible(false);
        passwordDeleted.setVisible(false);
        allPanel.setVisible(true);
        sites = UserDAO.viewAllSiteInfo();
        String line;
        String dPass;
        for(int i = 0; i < sites.size(); i++){
            dPass = KeyManager.getInstance().encryption(sites.get(i)[2], Integer.parseInt(sites.get(i)[1]), 2);
            line = sites.get(i)[0] + "\t" + dPass + "\n";
            allPass.append(line);
        }


    }//GEN-LAST:event_viewPassButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        this.dispose();
        LoginScreen login = new LoginScreen();
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void changeAccountSaveButtonActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_changeAccountSaveButtonActionPerformed
        String oldPass = new String(oldPassText.getPassword());
        String newPass = new String(newPassText.getPassword());
        if(u.getPassword().equals(oldPass)){
            passIncorrect.setVisible(false);
            UserDAO.updateAccountPassword(u.getUserName(), newPass);
            u.setPassword(newPass);
            passwordUpdate.setVisible(true);
            oldPassText.setText("");
            newPassText.setText("");
        }
        else{
            passIncorrect.setVisible(true);
            passwordUpdate.setVisible(false);
            oldPassText.setText("");
            newPassText.setText("");
        }
    }//GEN-LAST:event_changeAccountSaveButtonActionPerformed

    private void changeAccountDoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeAccountDoneButtonActionPerformed
        changePassPanel.setVisible(false);
    }//GEN-LAST:event_changeAccountDoneButtonActionPerformed

    private void addDoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDoneButtonActionPerformed
        addPanel.setVisible(false);
        savedPass.setVisible(false);
    }//GEN-LAST:event_addDoneButtonActionPerformed

    private void addSaveButtonActionPerformed(java.awt.event.ActionEvent evt){//GEN-FIRST:event_addSaveButtonActionPerformed
        int encryptType = encryptionComboBox.getSelectedIndex(); // 0 for AES, 1 for RDS
        String siteName = passNameText.getText();
        String addPass = new String(addPassText.getPassword());
        try {
            km.addCommand(encryptType, siteName, addPass, 1);
//            addUndoButton.setEnabled(true);
            savedPass.setText("Saved: " + passNameText.getText());
            passNameText.setText("");
            addPassText.setText("");
            savedPass.setVisible(true);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

    }//GEN-LAST:event_addSaveButtonActionPerformed

    private void editSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSaveButtonActionPerformed
        String siteName = enterNameText.getText();
        String editPass = new String(updatePassText.getPassword());
        try {
            km.editCommand(siteName, editPass, 1);
            enterNameText.setText("");
            updatePassText.setText("");
            passwordUpdated.setText("Password Updated");
            passwordUpdated.setVisible(true);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }//GEN-LAST:event_editSaveButtonActionPerformed

    private void editDoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDoneButtonActionPerformed
        editPanel.setVisible(false);
        passwordUpdated.setVisible(false);
    }//GEN-LAST:event_editDoneButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        String siteName = deleteText.getText();
        try {
            km.deleteCommand(siteName, 1);
            deleteText.setText("");
            passwordDeleted.setText("Password deleted");
            passwordDeleted.setVisible(true);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void deleteDoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDoneButtonActionPerformed
        deletePanel.setVisible(false);
        passwordDeleted.setVisible(false);
    }//GEN-LAST:event_deleteDoneButtonActionPerformed

    private void allDoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allDoneButtonActionPerformed
        allPanel.setVisible(false);
    }//GEN-LAST:event_allDoneButtonActionPerformed

    private void addUndoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUndoButtonActionPerformed
        int encryptType = encryptionComboBox.getSelectedIndex(); // 0 for AES, 1 for RDS
        String siteName = passNameText.getText();
        String addPass = addPassText.getText();
        try {
            km.addCommand(encryptType, siteName, addPass, 2);
            savedPass.setText("Password removed");
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }//GEN-LAST:event_addUndoButtonActionPerformed

    private void addRedoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRedoButtonActionPerformed
        int encryptType = encryptionComboBox.getSelectedIndex(); // 0 for AES, 1 for RDS
        String siteName = passNameText.getText();
        String addPass = addPassText.getText();
        try {
            km.addCommand(encryptType, siteName, addPass, 3);
            savedPass.setText("Password restored");
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }//GEN-LAST:event_addRedoButtonActionPerformed

    private void editUndoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUndoButtonActionPerformed
        String siteName = enterNameText.getText();
        String editPass = updatePassText.getText();
        try {
            km.editCommand(siteName, editPass, 2);
            passwordUpdated.setText("Password restored");
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }//GEN-LAST:event_editUndoButtonActionPerformed

    private void editRedoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editRedoButtonActionPerformed
        String siteName = enterNameText.getText();
        String editPass = updatePassText.getText();
        try {
            km.editCommand(siteName, editPass, 3);
            passwordUpdated.setText("Password restored");
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }//GEN-LAST:event_editRedoButtonActionPerformed

    private void deleteRedoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRedoButtonActionPerformed
        String siteName = deleteText.getText();
        try {
            km.deleteCommand(siteName, 3);
            passwordDeleted.setText("Password deleted");
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }//GEN-LAST:event_deleteRedoButtonActionPerformed

    private void deleteUndoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUndoButtonActionPerformed
        String siteName = deleteText.getText();
        try {
            km.deleteCommand(siteName, 2);
            passwordDeleted.setText("Password restored");
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }//GEN-LAST:event_deleteUndoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HomeScreen().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountManageLabel;
    private javax.swing.JButton addDoneButton;
    private javax.swing.JPanel addPanel;
    private javax.swing.JButton addPassButton;
    private javax.swing.JLabel addPassLabel;
    private javax.swing.JPasswordField addPassText;
    private javax.swing.JLabel addPassTitle;
    private javax.swing.JButton addRedoButton;
    private javax.swing.JButton addSaveButton;
    private javax.swing.JButton addUndoButton;
    private javax.swing.JButton allDoneButton;
    private javax.swing.JLabel allNameLabel;
    private javax.swing.JPanel allPanel;
    private javax.swing.JTextArea allPass;
    private javax.swing.JLabel allPassLabel;
    private javax.swing.JLabel allPassTitle;
    private javax.swing.JButton changeAccountDoneButton;
    private javax.swing.JButton changeAccountSaveButton;
    private javax.swing.JButton changePassButton;
    private javax.swing.JLabel changePassLabel;
    private javax.swing.JPanel changePassPanel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton deleteDoneButton;
    private javax.swing.JLabel deleteLabel;
    private javax.swing.JPanel deletePanel;
    private javax.swing.JButton deletePassButton;
    private javax.swing.JButton deleteRedoButton;
    private javax.swing.JTextField deleteText;
    private javax.swing.JLabel deleteTitle;
    private javax.swing.JButton deleteUndoButton;
    private javax.swing.JButton editDoneButton;
    private javax.swing.JPanel editPanel;
    private javax.swing.JButton editPassButton;
    private javax.swing.JButton editRedoButton;
    private javax.swing.JButton editSaveButton;
    private javax.swing.JLabel editTitle;
    private javax.swing.JButton editUndoButton;
    private javax.swing.JComboBox<String> encryptionComboBox;
    private javax.swing.JLabel encyrptionTypeLabel1;
    private javax.swing.JLabel encyrptionTypeLabel2;
    private javax.swing.JLabel enterNameLabel;
    private javax.swing.JTextField enterNameText;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel homeTitle;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logOutButton;
    private javax.swing.JLabel newPassLabel;
    private javax.swing.JPasswordField newPassText;
    private javax.swing.JLabel oldPassLabel;
    private javax.swing.JPasswordField oldPassText;
    private javax.swing.JLabel passIncorrect;
    private javax.swing.JLabel passManageLabel;
    private javax.swing.JLabel passNameLabel;
    private javax.swing.JTextField passNameText;
    private javax.swing.JLabel passwordDeleted;
    private javax.swing.JLabel passwordUpdate;
    private javax.swing.JLabel passwordUpdated;
    private javax.swing.JLabel savedPass;
    private javax.swing.JLayeredPane sidePanel;
    private javax.swing.JLabel updatePassLabel;
    private javax.swing.JPasswordField updatePassText;
    private javax.swing.JButton viewPassButton;
    // End of variables declaration//GEN-END:variables
}
